name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: codeberg-small

    steps:
    - uses: actions/checkout@v4
    - uses: wackbyte/rust-toolchain@trunk
      with:
        toolchain: stable
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Verify msrv
      run: cargo install cargo-msrv && cargo msrv verify

