name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-dev-noble

    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Verify msrv
        run: cargo msrv verify
